/////////////////////////////////////////////////////
// *** DO NOT EDIT MANUALLY ***
// This file is generated by the utility `idlx`.
/////////////////////////////////////////////////////

/////////////////////////////////////////////////
// Messages from: middle/middle_file.proto

pub struct Middle {
    pub str: String,
    pub i32: i32,
    pub root: super::BasicTypes,
    pub inner: inner::Inner,
}

pub struct SharedName {
    pub str: String,
}

/////////////////////////////////////////////////
// Messages from: middle/middle_imports.proto

pub struct Imports {
    pub root: super::BasicTypes,
    pub middle: Middle,
    pub inner: inner::Inner,
    pub root_shared: super::SharedName,
    pub middle_shared: SharedName,
    pub inner_shared: inner::SharedName,
}

